version = 0.1

[default.deploy.parameters]
stack_name = "landerv4"
resolve_s3 = true
s3_prefix = "landerv4"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
