services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: joblander
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Job-Lander Application
  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/joblander
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY:-demo-key-for-development}
      - CANVA_CLIENT_ID=${CANVA_CLIENT_ID:-demo-client-id}
      - CANVA_CLIENT_SECRET=${CANVA_CLIENT_SECRET:-demo-client-secret}
      - JSEARCH_API_KEY=${JSEARCH_API_KEY:-demo-jsearch-key}
      - SESSION_SECRET=development-session-secret-key-please-change-in-production
      - PRIVATE_KEY=0x0000000000000000000000000000000000000000000000000000000000000000
      - CONTRACT_ADDRESS=0x0000000000000000000000000000000000000000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data: