name: Deploy JobLander API to AWS

on:
  push:
    branches:
      - main  # change this if your main branch is called something else (like "master")

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Build Lambda
        run: sam build --use-container

      - name: Deploy Lambda to AWS
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name landerv4 \
          --region us-east-1 \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
